@postId = 6738b6d647545097428cbbe9
@commentId = 6738b9c30e8d99f8abfb5db3
@sender = user123

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~ Posts ~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Add a new post
POST http://localhost:3001/post
Content-Type: application/json

{
  "title": "My new comment Post",
  "content": "This is the content of my first post!",
  "sender": "{{sender}}"
}

###

# Get all posts
GET http://localhost:3001/post

###

# Get a post by ID
GET http://localhost:3001/post/{{postId}}

###

# Get posts by sender
GET http://localhost:3001/post?sender={{sender}}

###

# Update a post
PUT http://localhost:3001/post/{{postId}}
Content-Type: application/json

{
  "title": "My new comment Post - Updated",
  "content": "Updated content of my post!"
}

###

# Delete a post
DELETE http://localhost:3001/post/{{postId}}

###

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~ Comments ~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Get all comments for a post
GET http://localhost:3001/post/{{postId}}/comment
Content-Type: application/json

###

# Get a specific comment by ID
GET http://localhost:3001/post/{{postId}}/comment/{{commentId}}
Content-Type: application/json

###

# Create a new comment for a post
POST http://localhost:3001/post/{{postId}}/comment
Content-Type: application/json

{
  "content": "This is another comment3",
  "author": "{{sender}}"
}

###

# Update an existing comment
PUT http://localhost:3001/post/{{postId}}/comment/{{commentId}}
Content-Type: application/json

{
  "content": "This is a new comment - updated"
}

###

# Delete a comment
DELETE http://localhost:3001/post/{{postId}}/comment/{{commentId}}
Content-Type: application/json
